model_list:
  - model_name: qwen2_5-1_5b
    litellm_params:
      model: openai/qwen2_5-1_5b
      api_base: https://qwen1-5b.mlops-wzs.k8s.wistron.com/v1
      api_key: token-abc123

  - model_name: qwen2_5-7b
    litellm_params:
      model: hosted_vllm/qwen2_5-7b
      api_base: https://qwen7b.mlops-wzs.k8s.wistron.com/v1
      api_key: token-abc123

  - model_name: llama3.1-8b-instruct
    litellm_params:
      model: openai/llama3.1-8b-instruct
      api_base: https://llama3-8b.mlops-whq.k8s.wistron.com/v1
      api_key: sk-TYi1oIG49Z

  - model_name: llama3-guard-8b
    litellm_params:
      model: hosted_vllm/llama3-guard-8b
      api_base: https://llamaguard3-8b.mlops-whq.k8s.wistron.com/v1
      api_key: sk-05rrCPZ@!u_tx62
