model_list:
  - model_name: qwen2_5-1_5b
    litellm_params:
      model: openai/qwen2_5-1_5b
      api_base: https://qwen1-5b.mlops-wzs.k8s.wistron.com/v1
      api_key: token-abc123
  - model_name: qwen2_5-7b
    litellm_params:
      model: openai/qwen2_5-7b
      api_base: https://qwen7b.mlops-wzs.k8s.wistron.com/v1
      api_key: token-abc123