user_list:
  - user_token: sk-0000
    user_profile:
      id: 8703147
      name: "Erhwen, Kuo"
      project: test
      org: mlx000
  - user_token: sk-0001
    user_profile:
      id: 11309006
      name: "Ruby Lo"
      project: test
      org: mlx000